### ISSUE TITLE
Fatal error: Call to a member function getPropertyValues() on null in NotificationGroupsLocator

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticNotifications#14]
### Setup and configuration

- SMW version: all
- SNO version: 1.0-alpha
- MW version: all
- DB (MySQL etc.):

### Issue

Fatal error: Call to a member function getPropertyValues() on null in /var/www/htdocs/mw/02100/w/extensions/SemanticNotifications/src/ChangeNotification/NotificationGroupsLocator.php on line 81

http://sandbox.semantic-mediawiki.org/wiki/Bug/0001

**Comment by mwjames** [comment]
Expected to be fixed by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1883

**Comment by mwjames** [comment]
@kghbln FYI when reviewing the sandbox logs.

**Comment by kghbln** [comment]
I updated sandbox so sandbox is now on latest code.
