### ISSUE TITLE
Compatible with SWM 2.4.x?

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticNotifications#18]
### Setup
- MediaWiki 	1.28.0-rc.0 (7625c75) 15:14, 3. Nov. 2016
- PHP 	5.6.27-0+deb8u1 (apache2handler)
- MariaDB 	10.0.28-MariaDB-1~jessie
- SemanticNotifications master

### Issue

The README claims that SemanticNotifications is compatible with SMW 2.4.x. However after switching to 2.4.x I get

```
PHP Fatal error:  Call to undefined method SMWSql3SmwIds::getDataItemById() in /.../w/extensions/SemanticNotifications/src/ChangeNotification/ChangeNotificationFilter.php on line 192

Fatal error: Call to undefined method SMWSql3SmwIds::getDataItemById() in /.../w/extensions/SemanticNotifications/src/ChangeNotification/ChangeNotificationFilter.php on line 192
```
I guess this is just a matter of updating the README

**Comment by mwjames** [comment]
Good catch
