### ISSUE TITLE
Notifications via e-mail do not work

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticNotifications#9]
Continuing from https://github.com/SemanticMediaWiki/SemanticNotifications/issues/3#issuecomment-226936333

### Setup and configuration

MediaWiki 	1.27.0-rc.1 (5462877)
PHP 	5.6.22-0+deb8u1 (apache2handler)
Echo	– (13aaa9c)
SNO - master

### Issue

```
PHP Warning:  Illegal string offset 'subject' in /.../w/extensions/Echo/includes/Notifier.php on line 102
PHP Notice:  Uninitialized string offset: 0 in /.../w/extensions/Echo/includes/Notifier.php on line 102
PHP Warning:  Illegal string offset 'body' in /.../w/extensions/Echo/includes/Notifier.php on line 103
PHP Notice:  Uninitialized string offset: 0 in /.../w/extensions/Echo/includes/Notifier.php on line 103
PHP Warning:  Illegal string offset 'subject' in /.../w/extensions/Echo/includes/Notifier.php on line 102
PHP Notice:  Uninitialized string offset: 0 in /.../w/extensions/Echo/includes/Notifier.php on line 102
PHP Warning:  Illegal string offset 'body' in /.../w/extensions/Echo/includes/Notifier.php on line 103
PHP Notice:  Uninitialized string offset: 0 in /.../w/extensions/Echo/includes/Notifier.php on line 103
```
This popped up via the job queue. Perhaps this the cause. This may however very well be an issue to be reported for Echo itself.

**Comment by mwjames** [comment]
> Illegal string offset 'subject' in /.../w/extensions/Echo/includes/Notifier.php on line 102

This is "good" because it means it reached the email processor and "bad" Echo should not fail because of a missing message text key. I'd say, if you have time then let them know that doing 

```
$subject = $email['subject'];
$body = $email['body'];
```

without a `isset` check is ...

**Comment by mwjames** [comment]
@catrope FYI

**Comment by kghbln** [comment]
@mwjames As a service I created [task T138534](https://phabricator.wikimedia.org/T138534) for this.

**Comment by kghbln** [comment]
Echo will get an new [HTML email formatter using presentation model](https://phabricator.wikimedia.org/rECHO6f6e10084c1d9e5c34a0368fd5282945d2b79e24) starting REL1_28. Hopefully this allows e-mails to be send. If this will not work it will never work. So the minimum version requirement will be MW 1.28.0 I'm afraid.
